version: '3.9'

services:
  db:
    container_name: db
    image: mysql
    ports:
      - "1234:3306"
    environment:
      MYSQL_DATABASE: 'appDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
  web:
    image: web
    container_name: web
    build: ./web
    volumes:
      - ./src/dynamic:/var/www/html
    depends_on:
      - db
  proxy:
    image: nginx:1.11
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/data/static/